name: Deploy to Vercel

on:
  push:
    branches: [main]

jobs:
  vercel-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Vercel CLI
        run: npm i -g vercel@30

      - name: Setup pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install frontend dependencies
        working-directory: src/frontend
        run: pnpm install --frozen-lockfile

      - name: Build frontend
        working-directory: src/frontend
        run: pnpm build

      - name: Vercel Deploy
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          # Pass the token directly from the repository secret to avoid empty --token argument
          vercel deploy --prod --confirm --token ${{ secrets.VERCEL_TOKEN }} --cwd src/frontend
